/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: sanity/schema.json
export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  message?: string;
  link?: Link;
  variant?: "forest" | "amber";
  startsAt?: string;
  endsAt?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type RegionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "region";
};

export type PlaceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "place";
};

export type ExperienceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experience";
};

export type GuideReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "guide";
};

export type Link = {
  _type: "link";
  label?: string;
  kind?: "internal" | "external";
  internal?:
    | HomePageReference
    | PageReference
    | RegionReference
    | PlaceReference
    | ExperienceReference
    | GuideReference;
  external?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  tagline?: string;
  logo?: AccessibleImage;
  mainMenu?: Array<
    {
      _key: string;
    } & Link
  >;
  headerCta?: Link;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "footerColumn";
    _key: string;
  }>;
  email?: string;
  phone?: string;
  social?: Array<{
    network?:
      | "Instagram"
      | "Facebook"
      | "TikTok"
      | "YouTube"
      | "LinkedIn"
      | "Pinterest";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  company?: {
    legalName?: string;
    registrationNumber?: string;
    vatNumber?: string;
    address?: string;
  };
  defaultSeo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: AccessibleImage;
  noIndex?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  credit?: string;
};

export type SpacerBlock = {
  _type: "spacerBlock";
  size?: "small" | "medium" | "large";
  divider?: boolean;
};

export type VideoBlock = {
  _type: "videoBlock";
  url?: string;
  title?: string;
  poster?: AccessibleImage;
};

export type StatsBlock = {
  _type: "statsBlock";
  heading?: string;
  items?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
};

export type FaqBlock = {
  _type: "faqBlock";
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type TestimonialsBlock = {
  _type: "testimonialsBlock";
  heading?: string;
  items?: Array<{
    quote?: string;
    author?: string;
    origin?: string;
    _type: "testimonial";
    _key: string;
  }>;
};

export type GalleryBlock = {
  _type: "galleryBlock";
  heading?: string;
  images?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
};

export type CtaBandBlock = {
  _type: "ctaBandBlock";
  variant?: "forest" | "sea" | "sand";
  headline?: string;
  text?: string;
  action?: Link;
};

export type DestinationCardsBlock = {
  _type: "destinationCardsBlock";
  heading?: string;
  items?: ArrayOf<RegionReference | PlaceReference>;
};

export type ExperienceGridBlock = {
  _type: "experienceGridBlock";
  heading?: string;
  variant?: "grid" | "carousel";
  mode?: "manual" | "region";
  experiences?: Array<
    {
      _key: string;
    } & ExperienceReference
  >;
  region?: RegionReference;
  limit?: number;
};

export type RichTextBlock = {
  _type: "richTextBlock";
  variant?: "narrow" | "wide";
  body?: PortableText;
};

export type HeroBlock = {
  _type: "heroBlock";
  variant?: "image" | "split" | "minimal";
  eyebrow?: string;
  headline?: string;
  intro?: string;
  image?: AccessibleImage;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: PortableText;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & AccessibleImage)
>;

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: CategoryReference;
  author?: AuthorReference;
  publishedAt?: string;
  excerpt?: string;
  heroImage?: AccessibleImage;
  body?: Array<
    | ({
        _key: string;
      } & RichTextBlock)
    | ({
        _key: string;
      } & ExperienceGridBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & CtaBandBlock)
    | ({
        _key: string;
      } & VideoBlock)
    | ({
        _key: string;
      } & FaqBlock)
  >;
  related?: Array<
    {
      _key: string;
    } & GuideReference
  >;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  photo?: AccessibleImage;
  bio?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CancellationPolicyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cancellationPolicy";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  type?: "tour" | "activity" | "private" | "transfer";
  region?: RegionReference;
  places?: Array<
    {
      _key: string;
    } & PlaceReference
  >;
  summary?: string;
  highlights?: Array<string>;
  images?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  description?: PortableText;
  itinerary?: Array<{
    time?: string;
    title?: string;
    description?: string;
    _type: "itineraryStop";
    _key: string;
  }>;
  durationMinutes?: number;
  languages?: Array<string>;
  maxGroupSize?: number;
  included?: Array<string>;
  notIncluded?: Array<string>;
  meetingPoint?: {
    name?: string;
    instructions?: string;
    location?: Geopoint;
  };
  whatToBring?: Array<string>;
  cancellationPolicy?: CancellationPolicyReference;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  priceFromCents?: number;
  badges?: Array<string>;
  related?: Array<
    {
      _key: string;
    } & ExperienceReference
  >;
  seo?: Seo;
};

export type CancellationPolicy = {
  _id: string;
  _type: "cancellationPolicy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  rules?: Array<{
    hoursBefore?: number;
    refundPercent?: number;
    _type: "refundRule";
    _key: string;
  }>;
  text?: PortableText;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Place = {
  _id: string;
  _type: "place";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  region?: RegionReference;
  summary?: string;
  heroImage?: AccessibleImage;
  intro?: PortableText;
  gallery?: Array<
    {
      _key: string;
    } & AccessibleImage
  >;
  location?: Geopoint;
  quickFacts?: {
    fromRiga?: string;
    gettingThere?: string;
    bestSeason?: string;
  };
  seo?: Seo;
};

export type Region = {
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  heroImage?: AccessibleImage;
  intro?: PortableText;
  location?: Geopoint;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & RichTextBlock)
    | ({
        _key: string;
      } & ExperienceGridBlock)
    | ({
        _key: string;
      } & DestinationCardsBlock)
    | ({
        _key: string;
      } & CtaBandBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & StatsBlock)
    | ({
        _key: string;
      } & VideoBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & RichTextBlock)
    | ({
        _key: string;
      } & ExperienceGridBlock)
    | ({
        _key: string;
      } & DestinationCardsBlock)
    | ({
        _key: string;
      } & CtaBandBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & TestimonialsBlock)
    | ({
        _key: string;
      } & FaqBlock)
    | ({
        _key: string;
      } & StatsBlock)
    | ({
        _key: string;
      } & VideoBlock)
    | ({
        _key: string;
      } & SpacerBlock)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Redirect
  | Announcement
  | HomePageReference
  | PageReference
  | RegionReference
  | PlaceReference
  | ExperienceReference
  | GuideReference
  | Link
  | SiteSettings
  | Seo
  | SanityImageAssetReference
  | AccessibleImage
  | SpacerBlock
  | VideoBlock
  | StatsBlock
  | FaqBlock
  | TestimonialsBlock
  | GalleryBlock
  | CtaBandBlock
  | DestinationCardsBlock
  | ExperienceGridBlock
  | RichTextBlock
  | HeroBlock
  | FaqItem
  | PortableText
  | CategoryReference
  | AuthorReference
  | Guide
  | Author
  | Category
  | Slug
  | CancellationPolicyReference
  | Experience
  | CancellationPolicy
  | Geopoint
  | Place
  | Region
  | Page
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: src/modules/content/queries.ts
// Variable: settingsQuery
// Query: *[_id == "siteSettings"][0]{  siteName,  tagline,  logo{ asset, hotspot, crop, alt, credit },  mainMenu[]{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }},  headerCta{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }},  footerColumns[]{ title, links[]{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },  email,  phone,  social,  company,  defaultSeo{ title, description, image{ asset, hotspot, crop, alt, credit } }}
export type SettingsQueryResult =
  | {
      siteName: null;
      tagline: null;
      logo: null;
      mainMenu: null;
      headerCta: null;
      footerColumns: null;
      email: null;
      phone: null;
      social: null;
      company: null;
      defaultSeo: null;
    }
  | {
      siteName: string | null;
      tagline: string | null;
      logo: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        credit: string | null;
      } | null;
      mainMenu: Array<{
        label: string | null;
        kind: "external" | "internal" | null;
        external: string | null;
        internal:
          | {
              _type: "experience";
              slug: string | null;
              regionSlug: string | null;
            }
          | {
              _type: "guide";
              slug: string | null;
              regionSlug: null;
            }
          | {
              _type: "homePage";
              slug: null;
              regionSlug: null;
            }
          | {
              _type: "page";
              slug: string | null;
              regionSlug: null;
            }
          | {
              _type: "place";
              slug: string | null;
              regionSlug: string | null;
            }
          | {
              _type: "region";
              slug: string | null;
              regionSlug: null;
            }
          | null;
      }> | null;
      headerCta: {
        label: string | null;
        kind: "external" | "internal" | null;
        external: string | null;
        internal:
          | {
              _type: "experience";
              slug: string | null;
              regionSlug: string | null;
            }
          | {
              _type: "guide";
              slug: string | null;
              regionSlug: null;
            }
          | {
              _type: "homePage";
              slug: null;
              regionSlug: null;
            }
          | {
              _type: "page";
              slug: string | null;
              regionSlug: null;
            }
          | {
              _type: "place";
              slug: string | null;
              regionSlug: string | null;
            }
          | {
              _type: "region";
              slug: string | null;
              regionSlug: null;
            }
          | null;
      } | null;
      footerColumns: Array<{
        title: string | null;
        links: Array<{
          label: string | null;
          kind: "external" | "internal" | null;
          external: string | null;
          internal:
            | {
                _type: "experience";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "guide";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "homePage";
                slug: null;
                regionSlug: null;
              }
            | {
                _type: "page";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "place";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "region";
                slug: string | null;
                regionSlug: null;
              }
            | null;
        }> | null;
      }> | null;
      email: string | null;
      phone: string | null;
      social: Array<{
        network?:
          | "Facebook"
          | "Instagram"
          | "LinkedIn"
          | "Pinterest"
          | "TikTok"
          | "YouTube";
        url?: string;
        _type: "socialLink";
        _key: string;
      }> | null;
      company: {
        legalName?: string;
        registrationNumber?: string;
        vatNumber?: string;
        address?: string;
      } | null;
      defaultSeo: {
        title: string | null;
        description: string | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: src/modules/content/queries.ts
// Variable: announcementQuery
// Query: *[_id == "announcement" && enabled == true  && (!defined(startsAt) || startsAt <= now())  && (!defined(endsAt) || endsAt > now())][0]{ message, variant, link{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} }
export type AnnouncementQueryResult = {
  message: string | null;
  variant: "amber" | "forest" | null;
  link: {
    label: string | null;
    kind: "external" | "internal" | null;
    external: string | null;
    internal:
      | {
          _type: "experience";
          slug: string | null;
          regionSlug: string | null;
        }
      | {
          _type: "guide";
          slug: string | null;
          regionSlug: null;
        }
      | {
          _type: "homePage";
          slug: null;
          regionSlug: null;
        }
      | {
          _type: "page";
          slug: string | null;
          regionSlug: null;
        }
      | {
          _type: "place";
          slug: string | null;
          regionSlug: string | null;
        }
      | {
          _type: "region";
          slug: string | null;
          regionSlug: null;
        }
      | null;
  } | null;
} | null;

// Source: src/modules/content/queries.ts
// Variable: homePageQuery
// Query: *[_id == "homePage"][0]{ sections[]{  ...,  _type == "heroBlock" => { image{ asset, hotspot, crop, alt, credit }, actions[]{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },  _type == "ctaBandBlock" => { action{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },  _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },  _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },  _type == "destinationCardsBlock" => { "items": items[]->{  _id,  _type,  title,  "slug": slug.current,  "regionSlug": region->slug.current,  summary,  "image": heroImage{ asset, hotspot, crop, alt, credit }} },  _type == "experienceGridBlock" => {    "items": select(      mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }},      experiences[]->{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}    )  }}, seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } } }
export type HomePageQueryResult =
  | {
      sections: null;
      seo: null;
    }
  | {
      sections: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
      } | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "ctaBandBlock";
            variant?: "forest" | "sand" | "sea";
            headline?: string;
            text?: string;
            action: {
              label: string | null;
              kind: "external" | "internal" | null;
              external: string | null;
              internal:
                | {
                    _type: "experience";
                    slug: string | null;
                    regionSlug: string | null;
                  }
                | {
                    _type: "guide";
                    slug: string | null;
                    regionSlug: null;
                  }
                | {
                    _type: "homePage";
                    slug: null;
                    regionSlug: null;
                  }
                | {
                    _type: "page";
                    slug: string | null;
                    regionSlug: null;
                  }
                | {
                    _type: "place";
                    slug: string | null;
                    regionSlug: string | null;
                  }
                | {
                    _type: "region";
                    slug: string | null;
                    regionSlug: null;
                  }
                | null;
            } | null;
          }
        | {
            _key: string;
            _type: "destinationCardsBlock";
            heading?: string;
            items: Array<
              | {
                  _id: string;
                  _type: "place";
                  title: string | null;
                  slug: string | null;
                  regionSlug: string | null;
                  summary: string | null;
                  image: {
                    asset: SanityImageAssetReference | null;
                    hotspot: SanityImageHotspot | null;
                    crop: SanityImageCrop | null;
                    alt: string | null;
                    credit: string | null;
                  } | null;
                }
              | {
                  _id: string;
                  _type: "region";
                  title: string | null;
                  slug: string | null;
                  regionSlug: null;
                  summary: string | null;
                  image: {
                    asset: SanityImageAssetReference | null;
                    hotspot: SanityImageHotspot | null;
                    crop: SanityImageCrop | null;
                    alt: string | null;
                    credit: string | null;
                  } | null;
                }
            > | null;
          }
        | {
            _key: string;
            _type: "experienceGridBlock";
            heading?: string;
            variant?: "carousel" | "grid";
            mode?: "manual" | "region";
            experiences?: Array<
              {
                _key: string;
              } & ExperienceReference
            >;
            region?: RegionReference;
            limit?: number;
            items: Array<{
              _id: string;
              title: string | null;
              slug: string | null;
              summary: string | null;
              durationMinutes: number | null;
              priceFromCents: number | null;
              badges: Array<string> | null;
              region: string | null;
              image: {
                asset: SanityImageAssetReference | null;
                hotspot: SanityImageHotspot | null;
                crop: SanityImageCrop | null;
                alt: string | null;
                credit: string | null;
              } | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "faqBlock";
            heading?: string;
            items?: Array<
              {
                _key: string;
              } & FaqItem
            >;
          }
        | {
            _key: string;
            _type: "galleryBlock";
            heading?: string;
            images: Array<{
              asset: SanityImageAssetReference | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              alt: string | null;
              credit: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "heroBlock";
            variant?: "image" | "minimal" | "split";
            eyebrow?: string;
            headline?: string;
            intro?: string;
            image: {
              asset: SanityImageAssetReference | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              alt: string | null;
              credit: string | null;
            } | null;
            actions: Array<{
              label: string | null;
              kind: "external" | "internal" | null;
              external: string | null;
              internal:
                | {
                    _type: "experience";
                    slug: string | null;
                    regionSlug: string | null;
                  }
                | {
                    _type: "guide";
                    slug: string | null;
                    regionSlug: null;
                  }
                | {
                    _type: "homePage";
                    slug: null;
                    regionSlug: null;
                  }
                | {
                    _type: "page";
                    slug: string | null;
                    regionSlug: null;
                  }
                | {
                    _type: "place";
                    slug: string | null;
                    regionSlug: string | null;
                  }
                | {
                    _type: "region";
                    slug: string | null;
                    regionSlug: null;
                  }
                | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "richTextBlock";
            variant?: "narrow" | "wide";
            body?: PortableText;
          }
        | {
            _key: string;
            _type: "spacerBlock";
            size?: "large" | "medium" | "small";
            divider?: boolean;
          }
        | {
            _key: string;
            _type: "statsBlock";
            heading?: string;
            items?: Array<{
              value?: string;
              label?: string;
              _type: "stat";
              _key: string;
            }>;
          }
        | {
            _key: string;
            _type: "testimonialsBlock";
            heading?: string;
            items?: Array<{
              quote?: string;
              author?: string;
              origin?: string;
              _type: "testimonial";
              _key: string;
            }>;
          }
        | {
            _key: string;
            _type: "videoBlock";
            url?: string;
            title?: string;
            poster: {
              asset: SanityImageAssetReference | null;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              alt: string | null;
              credit: string | null;
            } | null;
          }
      > | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
      } | null;
    }
  | null;

// Source: src/modules/content/queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id, title, sections[]{  ...,  _type == "heroBlock" => { image{ asset, hotspot, crop, alt, credit }, actions[]{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },  _type == "ctaBandBlock" => { action{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },  _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },  _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },  _type == "destinationCardsBlock" => { "items": items[]->{  _id,  _type,  title,  "slug": slug.current,  "regionSlug": region->slug.current,  summary,  "image": heroImage{ asset, hotspot, crop, alt, credit }} },  _type == "experienceGridBlock" => {    "items": select(      mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }},      experiences[]->{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}    )  }}, seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }}
export type PageQueryResult = {
  _id: string;
  title: string | null;
  sections: Array<
    | {
        _key: string;
        _type: "ctaBandBlock";
        variant?: "forest" | "sand" | "sea";
        headline?: string;
        text?: string;
        action: {
          label: string | null;
          kind: "external" | "internal" | null;
          external: string | null;
          internal:
            | {
                _type: "experience";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "guide";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "homePage";
                slug: null;
                regionSlug: null;
              }
            | {
                _type: "page";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "place";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "region";
                slug: string | null;
                regionSlug: null;
              }
            | null;
        } | null;
      }
    | {
        _key: string;
        _type: "destinationCardsBlock";
        heading?: string;
        items: Array<
          | {
              _id: string;
              _type: "place";
              title: string | null;
              slug: string | null;
              regionSlug: string | null;
              summary: string | null;
              image: {
                asset: SanityImageAssetReference | null;
                hotspot: SanityImageHotspot | null;
                crop: SanityImageCrop | null;
                alt: string | null;
                credit: string | null;
              } | null;
            }
          | {
              _id: string;
              _type: "region";
              title: string | null;
              slug: string | null;
              regionSlug: null;
              summary: string | null;
              image: {
                asset: SanityImageAssetReference | null;
                hotspot: SanityImageHotspot | null;
                crop: SanityImageCrop | null;
                alt: string | null;
                credit: string | null;
              } | null;
            }
        > | null;
      }
    | {
        _key: string;
        _type: "experienceGridBlock";
        heading?: string;
        variant?: "carousel" | "grid";
        mode?: "manual" | "region";
        experiences?: Array<
          {
            _key: string;
          } & ExperienceReference
        >;
        region?: RegionReference;
        limit?: number;
        items: Array<{
          _id: string;
          title: string | null;
          slug: string | null;
          summary: string | null;
          durationMinutes: number | null;
          priceFromCents: number | null;
          badges: Array<string> | null;
          region: string | null;
          image: {
            asset: SanityImageAssetReference | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            alt: string | null;
            credit: string | null;
          } | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "faqBlock";
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "galleryBlock";
        heading?: string;
        images: Array<{
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "heroBlock";
        variant?: "image" | "minimal" | "split";
        eyebrow?: string;
        headline?: string;
        intro?: string;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
        actions: Array<{
          label: string | null;
          kind: "external" | "internal" | null;
          external: string | null;
          internal:
            | {
                _type: "experience";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "guide";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "homePage";
                slug: null;
                regionSlug: null;
              }
            | {
                _type: "page";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "place";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "region";
                slug: string | null;
                regionSlug: null;
              }
            | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "richTextBlock";
        variant?: "narrow" | "wide";
        body?: PortableText;
      }
    | {
        _key: string;
        _type: "spacerBlock";
        size?: "large" | "medium" | "small";
        divider?: boolean;
      }
    | {
        _key: string;
        _type: "statsBlock";
        heading?: string;
        items?: Array<{
          value?: string;
          label?: string;
          _type: "stat";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "testimonialsBlock";
        heading?: string;
        items?: Array<{
          quote?: string;
          author?: string;
          origin?: string;
          _type: "testimonial";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "videoBlock";
        url?: string;
        title?: string;
        poster: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
} | null;

// Source: src/modules/content/queries.ts
// Variable: regionQuery
// Query: *[_type == "region" && slug.current == $slug][0]{  _id,  title,  summary,  intro,  heroImage{ asset, hotspot, crop, alt, credit },  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } },  "places": *[_type == "place" && region._ref == ^._id && defined(slug.current)] | order(title asc){  _id,  _type,  title,  "slug": slug.current,  "regionSlug": region->slug.current,  summary,  "image": heroImage{ asset, hotspot, crop, alt, credit }},  "experiences": *[_type == "experience" && region._ref == ^._id && defined(slug.current)] | order(title asc){  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}}
export type RegionQueryResult = {
  _id: string;
  title: string | null;
  summary: string | null;
  intro: PortableText | null;
  heroImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
  places: Array<{
    _id: string;
    _type: "place";
    title: string | null;
    slug: string | null;
    regionSlug: string | null;
    summary: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  }>;
  experiences: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    durationMinutes: number | null;
    priceFromCents: number | null;
    badges: Array<string> | null;
    region: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  }>;
} | null;

// Source: src/modules/content/queries.ts
// Variable: placeQuery
// Query: *[_type == "place" && slug.current == $slug && region->slug.current == $region][0]{  _id,  title,  summary,  intro,  heroImage{ asset, hotspot, crop, alt, credit },  gallery[]{ asset, hotspot, crop, alt, credit },  quickFacts,  "region": region->{ title, "slug": slug.current },  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } },  "experiences": *[_type == "experience" && ^._id in places[]._ref && defined(slug.current)] | order(title asc){  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}}
export type PlaceQueryResult = {
  _id: string;
  title: string | null;
  summary: string | null;
  intro: PortableText | null;
  heroImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
  gallery: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  }> | null;
  quickFacts: {
    fromRiga?: string;
    gettingThere?: string;
    bestSeason?: string;
  } | null;
  region: {
    title: string | null;
    slug: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
  experiences: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    durationMinutes: number | null;
    priceFromCents: number | null;
    badges: Array<string> | null;
    region: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  }>;
} | null;

// Source: src/modules/content/queries.ts
// Variable: regionsQuery
// Query: *[_type == "region" && defined(slug.current)] | order(title asc){  _id,  _type,  title,  "slug": slug.current,  "regionSlug": region->slug.current,  summary,  "image": heroImage{ asset, hotspot, crop, alt, credit }}
export type RegionsQueryResult = Array<{
  _id: string;
  _type: "region";
  title: string | null;
  slug: string | null;
  regionSlug: null;
  summary: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
}>;

// Source: src/modules/content/queries.ts
// Variable: experiencesQuery
// Query: *[_type == "experience" && defined(slug.current)] | order(title asc){  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}
export type ExperiencesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  durationMinutes: number | null;
  priceFromCents: number | null;
  badges: Array<string> | null;
  region: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
}>;

// Source: src/modules/content/queries.ts
// Variable: experienceQuery
// Query: *[_type == "experience" && slug.current == $slug][0]{  _id,  title,  type,  summary,  highlights,  images[]{ asset, hotspot, crop, alt, credit },  description,  itinerary,  durationMinutes,  languages,  maxGroupSize,  included,  notIncluded,  meetingPoint,  whatToBring,  priceFromCents,  badges,  faq,  "region": region->{ title, "slug": slug.current },  "cancellationPolicy": cancellationPolicy->{ title, text },  "related": related[]->{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }},  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }}
export type ExperienceQueryResult = {
  _id: string;
  title: string | null;
  type: "activity" | "private" | "tour" | "transfer" | null;
  summary: string | null;
  highlights: Array<string> | null;
  images: Array<{
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  }> | null;
  description: PortableText | null;
  itinerary: Array<{
    time?: string;
    title?: string;
    description?: string;
    _type: "itineraryStop";
    _key: string;
  }> | null;
  durationMinutes: number | null;
  languages: Array<string> | null;
  maxGroupSize: number | null;
  included: Array<string> | null;
  notIncluded: Array<string> | null;
  meetingPoint: {
    name?: string;
    instructions?: string;
    location?: Geopoint;
  } | null;
  whatToBring: Array<string> | null;
  priceFromCents: number | null;
  badges: Array<string> | null;
  faq: Array<
    {
      _key: string;
    } & FaqItem
  > | null;
  region: {
    title: string | null;
    slug: string | null;
  } | null;
  cancellationPolicy: {
    title: string | null;
    text: PortableText | null;
  } | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    durationMinutes: number | null;
    priceFromCents: number | null;
    badges: Array<string> | null;
    region: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
} | null;

// Source: src/modules/content/queries.ts
// Variable: guidesQuery
// Query: *[_type == "guide" && defined(slug.current)] | order(publishedAt desc){  _id, title, "slug": slug.current, excerpt, publishedAt, "category": category->title, "image": heroImage{ asset, hotspot, crop, alt, credit }}
export type GuidesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  category: string | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
}>;

// Source: src/modules/content/queries.ts
// Variable: guideQuery
// Query: *[_type == "guide" && slug.current == $slug][0]{  _id,  title,  excerpt,  publishedAt,  heroImage{ asset, hotspot, crop, alt, credit },  "category": category->title,  "author": author->{ name, bio, photo{ asset, hotspot, crop, alt, credit } },  "sections": body[]{    ...,    _type == "ctaBandBlock" => { action{  label,  kind,  external,  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }} },    _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },    _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },    _type == "experienceGridBlock" => {      "items": select(        mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }},        experiences[]->{  _id,  title,  "slug": slug.current,  summary,  durationMinutes,  priceFromCents,  badges,  "region": region->title,  "image": images[0]{ asset, hotspot, crop, alt, credit }}      )    }  },  "related": related[]->{ _id, title, "slug": slug.current, excerpt, publishedAt, "category": category->title, "image": heroImage{ asset, hotspot, crop, alt, credit } },  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }}
export type GuideQueryResult = {
  _id: string;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  heroImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    credit: string | null;
  } | null;
  category: string | null;
  author: {
    name: string | null;
    bio: string | null;
    photo: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
  sections: Array<
    | {
        _key: string;
        _type: "ctaBandBlock";
        variant?: "forest" | "sand" | "sea";
        headline?: string;
        text?: string;
        action: {
          label: string | null;
          kind: "external" | "internal" | null;
          external: string | null;
          internal:
            | {
                _type: "experience";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "guide";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "homePage";
                slug: null;
                regionSlug: null;
              }
            | {
                _type: "page";
                slug: string | null;
                regionSlug: null;
              }
            | {
                _type: "place";
                slug: string | null;
                regionSlug: string | null;
              }
            | {
                _type: "region";
                slug: string | null;
                regionSlug: null;
              }
            | null;
        } | null;
      }
    | {
        _key: string;
        _type: "experienceGridBlock";
        heading?: string;
        variant?: "carousel" | "grid";
        mode?: "manual" | "region";
        experiences?: Array<
          {
            _key: string;
          } & ExperienceReference
        >;
        region?: RegionReference;
        limit?: number;
        items: Array<{
          _id: string;
          title: string | null;
          slug: string | null;
          summary: string | null;
          durationMinutes: number | null;
          priceFromCents: number | null;
          badges: Array<string> | null;
          region: string | null;
          image: {
            asset: SanityImageAssetReference | null;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            alt: string | null;
            credit: string | null;
          } | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "faqBlock";
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "galleryBlock";
        heading?: string;
        images: Array<{
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "richTextBlock";
        variant?: "narrow" | "wide";
        body?: PortableText;
      }
    | {
        _key: string;
        _type: "videoBlock";
        url?: string;
        title?: string;
        poster: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: string | null;
          credit: string | null;
        } | null;
      }
  > | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    publishedAt: string | null;
    category: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      credit: string | null;
    } | null;
  } | null;
} | null;

// Source: src/modules/content/queries.ts
// Variable: sitemapQuery
// Query: *[_type in ["page", "region", "place", "experience", "guide"] && defined(slug.current) && seo.noIndex != true]{  _type, _updatedAt, "slug": slug.current, "regionSlug": region->slug.current}
export type SitemapQueryResult = Array<
  | {
      _type: "experience";
      _updatedAt: string;
      slug: string | null;
      regionSlug: string | null;
    }
  | {
      _type: "guide";
      _updatedAt: string;
      slug: string | null;
      regionSlug: null;
    }
  | {
      _type: "page";
      _updatedAt: string;
      slug: string | null;
      regionSlug: null;
    }
  | {
      _type: "place";
      _updatedAt: string;
      slug: string | null;
      regionSlug: string | null;
    }
  | {
      _type: "region";
      _updatedAt: string;
      slug: string | null;
      regionSlug: null;
    }
>;

// Source: src/modules/content/queries.ts
// Variable: redirectsQuery
// Query: *[_type == "redirect" && defined(from) && defined(to)]{ from, to, permanent }
export type RedirectsQueryResult = Array<{
  from: string;
  to: string;
  permanent: boolean | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  siteName,\n  tagline,\n  logo{ asset, hotspot, crop, alt, credit },\n  mainMenu[]{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n},\n  headerCta{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n},\n  footerColumns[]{ title, links[]{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n  email,\n  phone,\n  social,\n  company,\n  defaultSeo{ title, description, image{ asset, hotspot, crop, alt, credit } }\n}': SettingsQueryResult;
    '*[_id == "announcement" && enabled == true\n  && (!defined(startsAt) || startsAt <= now())\n  && (!defined(endsAt) || endsAt > now())][0]{ message, variant, link{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} }': AnnouncementQueryResult;
    '*[_id == "homePage"][0]{ sections[]{\n  ...,\n  _type == "heroBlock" => { image{ asset, hotspot, crop, alt, credit }, actions[]{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n  _type == "ctaBandBlock" => { action{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n  _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },\n  _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },\n  _type == "destinationCardsBlock" => { "items": items[]->{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  "regionSlug": region->slug.current,\n  summary,\n  "image": heroImage{ asset, hotspot, crop, alt, credit }\n} },\n  _type == "experienceGridBlock" => {\n    "items": select(\n      mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n},\n      experiences[]->{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}\n    )\n  }\n}, seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } } }': HomePageQueryResult;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id, title, sections[]{\n  ...,\n  _type == "heroBlock" => { image{ asset, hotspot, crop, alt, credit }, actions[]{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n  _type == "ctaBandBlock" => { action{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n  _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },\n  _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },\n  _type == "destinationCardsBlock" => { "items": items[]->{\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  "regionSlug": region->slug.current,\n  summary,\n  "image": heroImage{ asset, hotspot, crop, alt, credit }\n} },\n  _type == "experienceGridBlock" => {\n    "items": select(\n      mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n},\n      experiences[]->{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}\n    )\n  }\n}, seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }\n}': PageQueryResult;
    '*[_type == "region" && slug.current == $slug][0]{\n  _id,\n  title,\n  summary,\n  intro,\n  heroImage{ asset, hotspot, crop, alt, credit },\n  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } },\n  "places": *[_type == "place" && region._ref == ^._id && defined(slug.current)] | order(title asc){\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  "regionSlug": region->slug.current,\n  summary,\n  "image": heroImage{ asset, hotspot, crop, alt, credit }\n},\n  "experiences": *[_type == "experience" && region._ref == ^._id && defined(slug.current)] | order(title asc){\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}\n}': RegionQueryResult;
    '*[_type == "place" && slug.current == $slug && region->slug.current == $region][0]{\n  _id,\n  title,\n  summary,\n  intro,\n  heroImage{ asset, hotspot, crop, alt, credit },\n  gallery[]{ asset, hotspot, crop, alt, credit },\n  quickFacts,\n  "region": region->{ title, "slug": slug.current },\n  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } },\n  "experiences": *[_type == "experience" && ^._id in places[]._ref && defined(slug.current)] | order(title asc){\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}\n}': PlaceQueryResult;
    '*[_type == "region" && defined(slug.current)] | order(title asc){\n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  "regionSlug": region->slug.current,\n  summary,\n  "image": heroImage{ asset, hotspot, crop, alt, credit }\n}': RegionsQueryResult;
    '*[_type == "experience" && defined(slug.current)] | order(title asc){\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}': ExperiencesQueryResult;
    '*[_type == "experience" && slug.current == $slug][0]{\n  _id,\n  title,\n  type,\n  summary,\n  highlights,\n  images[]{ asset, hotspot, crop, alt, credit },\n  description,\n  itinerary,\n  durationMinutes,\n  languages,\n  maxGroupSize,\n  included,\n  notIncluded,\n  meetingPoint,\n  whatToBring,\n  priceFromCents,\n  badges,\n  faq,\n  "region": region->{ title, "slug": slug.current },\n  "cancellationPolicy": cancellationPolicy->{ title, text },\n  "related": related[]->{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n},\n  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }\n}': ExperienceQueryResult;
    '*[_type == "guide" && defined(slug.current)] | order(publishedAt desc){\n  _id, title, "slug": slug.current, excerpt, publishedAt, "category": category->title, "image": heroImage{ asset, hotspot, crop, alt, credit }\n}': GuidesQueryResult;
    '*[_type == "guide" && slug.current == $slug][0]{\n  _id,\n  title,\n  excerpt,\n  publishedAt,\n  heroImage{ asset, hotspot, crop, alt, credit },\n  "category": category->title,\n  "author": author->{ name, bio, photo{ asset, hotspot, crop, alt, credit } },\n  "sections": body[]{\n    ...,\n    _type == "ctaBandBlock" => { action{\n  label,\n  kind,\n  external,\n  "internal": internal->{ _type, "slug": slug.current, "regionSlug": region->slug.current }\n} },\n    _type == "galleryBlock" => { images[]{ asset, hotspot, crop, alt, credit } },\n    _type == "videoBlock" => { poster{ asset, hotspot, crop, alt, credit } },\n    _type == "experienceGridBlock" => {\n      "items": select(\n        mode == "region" => *[_type == "experience" && region._ref == ^.region._ref && defined(slug.current)] | order(title asc) [0...12]{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n},\n        experiences[]->{\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  durationMinutes,\n  priceFromCents,\n  badges,\n  "region": region->title,\n  "image": images[0]{ asset, hotspot, crop, alt, credit }\n}\n      )\n    }\n  },\n  "related": related[]->{ _id, title, "slug": slug.current, excerpt, publishedAt, "category": category->title, "image": heroImage{ asset, hotspot, crop, alt, credit } },\n  seo{ title, description, noIndex, image{ asset, hotspot, crop, alt, credit } }\n}': GuideQueryResult;
    '*[_type in ["page", "region", "place", "experience", "guide"] && defined(slug.current) && seo.noIndex != true]{\n  _type, _updatedAt, "slug": slug.current, "regionSlug": region->slug.current\n}': SitemapQueryResult;
    '*[_type == "redirect" && defined(from) && defined(to)]{ from, to, permanent }': RedirectsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
